### ISSUE TITLE
Display the name of the provider

### ISSUE THREAD

**Issue by ysavary** [winds-mobi/winds-mobi-client-garmin#6]
It is important for weather data providers who allow winds.mobi to use their data for free to display their name, ie "meteoswiss.ch" or "holfuy.com"

**Comment by s-reynier** [comment]
Hello @ysavary 
Thanks for the information, I add this feature in my todo list.
Can you confirm that winds.mobi api return always the name of data provider ?

**Comment by ysavary** [comment]
Yes, for each station, you will get the `pv-name` of the station: https://winds.mobi/api/2.2/stations/?limit=20&keys=pv-code&keys=pv-name

**Comment by s-reynier** [comment]
Hi @ysavary I added the name of weather provider in the last version of application (available on Garmin IQ)
